name: Create PR assets

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build assets
    strategy:
      matrix:
        include:
          - target: windows
          - target: linux
          - target: darwin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Build project
        run: make ${{ matrix.target }}
      - name: Upload amd64 build artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.target != 'windows' }}
        with:
          name: ${{ matrix.target }}-amd64
          path: "build/infracost-${{ matrix.target }}-amd64"
      - name: Upload windows amd64 build artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.target == 'windows' }}
        with:
          name: ${{ matrix.target }}-amd64
          path: "build/infracost.exe"
      - name: Upload arm64 build artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.target != 'windows' }}
        with:
          name: ${{ matrix.target }}-arm64
          path: "build/infracost-${{ matrix.target }}-arm64"
      - name: Upload windows arm64 build artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.target == 'windows' }}
        with:
          name: ${{ matrix.target }}-arm64
          path: "build/infracost-arm64.exe"

